// example data for reviews
const db = require('./index.js');
const Review = require('./schemas.js');

let samples = [
    {
        title: 'Underwhelming tbh',
        rating: 2,
        user: 'BigTymeG@m3r411',
        body: 'i thought this game was going to be amazing but it really was not.  Nice job making a game we have already seen before.  Sheesh, if i wanted to play an old dumb game, i would have played tag with the homies.  Do not buy if you enjoy originality!!!',
        pics: [],
        recommended: false,
        helpfulCount: 2,
        unhelpfulCount: 1,
        verified: false,
        purchasedDate: new Date('August 19, 2019 23:15:30'),
        comments: [{
            user: 'Blake',
            body: 'dude, like, get over it man'
        },
        {
            user: 'Karen',
            body: 'I agree.  We should report them'
        }]
    },
    {
        title: 'Pretty great',
        rating: 5,
        user: 'justAguy',
        body: 'Easily one of the best games i have played in a while.  You should all buy it!!!! pls!',
        pics: [{ url: 'https://www.pokemon-sunmoon.com/media/uploads/og_images/facebook-share-image-usa.jpg' }],
        recommended: true,
        helpfulCount: 3,
        verified: true,
        purchasedDate: new Date('March 12, 2020 12:15:30'),
        comments: [{
            user: 'Blake',
            body: 'dude, you are much cooler than the last guy i commented on'
        }]
    },
    {
        title: 'Mostly meh',
        rating: 3,
        user: 'Joe',
        body: 'I thought the game was fine.  Not great but not terrible either. Not as awesome as the rest of the games in my collection',
        pics: [{ url: 'https://i.ytimg.com/vi/rNMDQuRHUkE/maxresdefault.jpg' }, { url: 'https://i.pinimg.com/564x/bb/19/72/bb1972cbb87dbd0171be319d983ca438.jpg' }],
        recommended: false,
        verified: true,
        purchasedDate: new Date('June 11, 2019 05:25:43'),
        comments: []
    },
    {
        title: 'Not purchased but i love it!',
        rating: 5,
        user: 'Billy',
        body: 'Instant classic and one of the best games of all time.  I have not bought it yet but i cannot wait!!!',
        pics: [{ url: 'https://i.ytimg.com/vi/rNMDQuRHUkE/maxresdefault.jpg' }, { url: 'https://i.pinimg.com/564x/bb/19/72/bb1972cbb87dbd0171be319d983ca438.jpg' }],
        recommended: true,
        unhelpfulCount: 4,
        verified: false,
        comments: [{
            user: 'Tommy',
            body: 'Can you talk about a game you do not own??'
        }]
    },
    {
        "title": "nulla.", "rating": 4, "user": "Nathan", "body": "auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor", "pics": [{ url: "https pic" }], "helpfulCount": 33, "unhelpfulCount": 11, "recommended": true, "verified": false, "purchasedDate": new Date("May 29, 2018"), "comments": [{ "user": "Cailin", "body": "sodales nisi magna sed dui. Fusce aliquam,", "helpfulCount": 43, "unhelpfulCount": 82, "date": "August 12, 2019, " },
        { "user": "Lionel", "body": "Cum sociis", "helpfulCount": 27, "unhelpfulCount": 26, "date": "May 28, 2018, " },
        { "user": "Reagan", "body": "Quisque ornare tortor at risus. Nunc ac sem", "helpfulCount": 39, "unhelpfulCount": 5, "date": "September 1, 2018, " },
        { "user": "Laurel", "body": "lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc", "helpfulCount": 61, "unhelpfulCount": 46, "date": "May 21, 2019, " }]
    },
    {
        "title": "orci tincidunt adipiscing. Mauris molestie pharetra", "rating": 5, "user": "Zachary", "body": "Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam", "pics": [{ url: "https pic" }], "helpfulCount": 54, "unhelpfulCount": 40, "recommended": true, "verified": false, "purchasedDate": new Date("December 20, 2018"), "comments": [{ "user": "Tobias", "body": "aliquet, sem", "helpfulCount": 10, "unhelpfulCount": 68, "date": "February 20, 2020, " },
        { "user": "Tate", "body": "arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus.", "helpfulCount": 55, "unhelpfulCount": 10, "date": "June 26, 2019, " },
        { "user": "Yeo", "body": "Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor.", "helpfulCount": 84, "unhelpfulCount": 36, "date": "November 14, 2018, " }]
    },
    { "title": "semper.", "rating": 4, "user": "Summer", "body": "Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis", "pics": [{ url: "https pic" }], "helpfulCount": 66, "unhelpfulCount": 19, "recommended": true, "verified": false, "purchasedDate": new Date("May 30, 2018"), "comments": [] },
    { "title": "dolor vitae", "rating": 4, "user": "Kylynn", "body": "eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at,", "pics": [{ url: "https pic" }], "helpfulCount": 51, "unhelpfulCount": 65, "recommended": true, "verified": false, "purchasedDate": new Date("June 8, 2018"), "comments": [] },
    { "title": "ac risus. Morbi", "rating": 2, "user": "Zenia", "body": "sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum", "pics": [{ url: "https pic" }], "helpfulCount": 67, "unhelpfulCount": 65, "recommended": false, "verified": false, "purchasedDate": new Date("April 27, 2018"), "comments": [] },
    { "title": "turpis egestas.", "rating": 5, "user": "Piper", "body": "libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque.", "pics": [{ url: "https pic" }], "helpfulCount": 66, "unhelpfulCount": 32, "recommended": true, "verified": true, "purchasedDate": new Date("June 6, 2018"), "comments": [{ "user": "Ashton", "body": "risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at,", "helpfulCount": 33, "unhelpfulCount": 52, "date": "May 4, 2019, " }] },
    { "title": "blandit enim consequat purus.", "rating": 2, "user": "Chandler", "body": "feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna.", "pics": [{ url: "https pic" }], "helpfulCount": 13, "unhelpfulCount": 5, "recommended": false, "verified": true, "purchasedDate": new Date("August 20, 2018"), "comments": [] },
    { "title": "tortor, dictum", "rating": 5, "user": "Dean", "body": "massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum", "pics": [{ url: "https pic" }], "helpfulCount": 81, "unhelpfulCount": 44, "recommended": true, "verified": true, "purchasedDate": new Date("March 5, 2020"), "comments": [] },
    { "title": "ac, feugiat non, lobortis quis, pede.", "rating": 2, "user": "Hadassah", "body": "Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum", "pics": [{ url: "https pic" }], "helpfulCount": 100, "unhelpfulCount": 76, "recommended": true, "verified": false, "purchasedDate": new Date("September 14, 2019"), "comments": [] },
    { "title": "ut nisi a odio semper", "rating": 2, "user": "Bree", "body": "et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet", "pics": [{ url: "https pic" }], "helpfulCount": 83, "unhelpfulCount": 90, "recommended": true, "verified": false, "purchasedDate": new Date("August 15, 2019"), "comments": [{ "user": "Denise", "body": "nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit", "helpfulCount": 55, "unhelpfulCount": 7, "date": "July 1, 2018, " }] },
    { "title": "sed pede. Cum sociis natoque penatibus", "rating": 5, "user": "Sonia", "body": "sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna.", "pics": [{ url: "https pic" }], "helpfulCount": 30, "unhelpfulCount": 81, "recommended": true, "verified": false, "purchasedDate": new Date("August 20, 2019"), "comments": [] },
    { "title": "facilisis lorem tristique", "rating": 2, "user": "Laith", "body": "vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et", "pics": [{ url: "https pic" }], "helpfulCount": 14, "unhelpfulCount": 37, "recommended": true, "verified": true, "purchasedDate": new Date("June 20, 2019"), "comments": [] },
    {
        "title": "consequat dolor vitae dolor. Donec", "rating": 1, "user": "Gregory", "body": "vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor", "pics": [{ url: "https pic" }], "helpfulCount": 31, "unhelpfulCount": 55, "recommended": true, "verified": true, "purchasedDate": new Date("August 21, 2018"), "comments": [{ "user": "Edan", "body": "lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In", "helpfulCount": 57, "unhelpfulCount": 54, "date": "May 24, 2019, " },
        { "user": "Jacqueline", "body": "Vivamus euismod urna. Nullam lobortis quam a felis", "helpfulCount": 23, "unhelpfulCount": 21, "date": "February 6, 2020, " }]
    },
    { "title": "est tempor bibendum. Donec felis orci,", "rating": 4, "user": "Jaquelyn", "body": "eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa.", "pics": [{ url: "https pic" }], "helpfulCount": 55, "unhelpfulCount": 55, "recommended": false, "verified": true, "purchasedDate": new Date("January 18, 2020"), "comments": [] },
    { "title": "nisi. Cum sociis natoque", "rating": 1, "user": "Eaton", "body": "diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et", "pics": [{ url: "https pic" }], "helpfulCount": 19, "unhelpfulCount": 91, "recommended": true, "verified": true, "purchasedDate": new Date("June 21, 2019"), "comments": [{ "user": "Amber", "body": "luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi.", "helpfulCount": 79, "unhelpfulCount": 2, "date": "February 11, 2020, " }] },
    {
        "title": "lorem, auctor quis, tristique", "rating": 2, "user": "Galvin", "body": "turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam", "pics": [{ url: "https pic" }], "helpfulCount": 19, "unhelpfulCount": 13, "recommended": true, "verified": false, "purchasedDate": new Date("January 7, 2019"), "comments": [{ "user": "Yvette", "body": "mi. Duis risus odio, auctor vitae,", "helpfulCount": 12, "unhelpfulCount": 18, "date": "June 25, 2018, " },
        { "user": "Troy", "body": "vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non,", "helpfulCount": 51, "unhelpfulCount": 28, "date": "August 19, 2019, " },
        { "user": "Holmes", "body": "parturient montes, nascetur ridiculus mus. Proin vel", "helpfulCount": 36, "unhelpfulCount": 11, "date": "November 12, 2018, " },
        { "user": "Wanda", "body": "Duis sit amet diam eu dolor egestas rhoncus.", "helpfulCount": 97, "unhelpfulCount": 2, "date": "February 21, 2020, " },
        { "user": "Dieter", "body": "non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum", "helpfulCount": 20, "unhelpfulCount": 68, "date": "January 25, 2020, " },
        { "user": "Avye", "body": "Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo", "helpfulCount": 15, "unhelpfulCount": 10, "date": "October 2, 2019, " },
        { "user": "Yeo", "body": "lacus. Etiam bibendum fermentum metus. Aenean sed pede", "helpfulCount": 84, "unhelpfulCount": 29, "date": "November 3, 2019, " }]
    },
    {
        "title": "velit eget laoreet posuere,", "rating": 1, "user": "Destiny", "body": "non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras", "pics": [{ url: "https pic" }], "helpfulCount": 32, "unhelpfulCount": 34, "recommended": true, "verified": false, "purchasedDate": new Date("May 12, 2019"), "comments": []
    },
    {
        "title": "dictum eu, eleifend nec, malesuada", "rating": 2, "user": "Barclay", "body": "amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere, enim nisl", "pics": [{ url: "https pic" }], "helpfulCount": 61, "unhelpfulCount": 5, "recommended": false, "verified": true, "purchasedDate": new Date("March 12, 2019"), "comments": [{ "user": "Catherine", "body": "Nunc pulvinar arcu et pede. Nunc sed", "helpfulCount": 11, "unhelpfulCount": 91, "date": "April 20, 2018, " }]
    },
    { "title": "a odio semper cursus. Integer mollis. Integer", "rating": 3, "user": "Hadley", "body": "Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur", "pics": [{ url: "https pic" }], "helpfulCount": 9, "unhelpfulCount": 89, "recommended": true, "verified": true, "purchasedDate": new Date("November 11, 2019"), "comments": [] },
    { "title": "sapien,", "rating": 5, "user": "Kiara", "body": "dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet", "pics": [{ url: "https pic" }], "helpfulCount": 4, "unhelpfulCount": 3, "recommended": false, "verified": true, "purchasedDate": new Date("January 1, 2020"), "comments": [{ "user": "Zeph", "body": "Donec feugiat metus sit amet", "helpfulCount": 8, "unhelpfulCount": 95, "date": "October 9, 2018, " }] },
    {
        "title": "ipsum dolor", "rating": 3, "user": "Kaseem", "body": "lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis", "pics": [{ url: "https pic" }], "helpfulCount": 16, "unhelpfulCount": 71, "recommended": false, "verified": true, "purchasedDate": new Date("May 26, 2018"), "comments": [{ "user": "Caldwell", "body": "elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare,", "helpfulCount": 75, "unhelpfulCount": 78, "date": "November 14, 2018, " },
        { "user": "Kelly", "body": "Cum sociis", "helpfulCount": 69, "unhelpfulCount": 27, "date": "June 3, 2019, " },
        { "user": "Martha", "body": "quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula.", "helpfulCount": 53, "unhelpfulCount": 18, "date": "July 27, 2019, " }]
    },
    { "title": "nascetur", "rating": 5, "user": "Veronica", "body": "est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui", "pics": [{ url: "https pic" }], "helpfulCount": 55, "unhelpfulCount": 44, "recommended": false, "verified": true, "purchasedDate": new Date("December 1, 2019"), "comments": [] },
    { "title": "eget massa. Suspendisse", "rating": 3, "user": "Perry", "body": "vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt", "pics": [{ url: "https pic" }], "helpfulCount": 13, "unhelpfulCount": 71, "recommended": true, "verified": false, "purchasedDate": new Date("August 4, 2018"), "comments": [] },
    { "title": "vitae risus.", "rating": 5, "user": "Camilla", "body": "enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros", "pics": [{ url: "https pic" }], "helpfulCount": 29, "unhelpfulCount": 88, "recommended": true, "verified": true, "purchasedDate": new Date("March 2, 2020"), "comments": [] },
    { "title": "et", "rating": 4, "user": "Wade", "body": "ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus.", "pics": [{ url: "https pic" }], "helpfulCount": 47, "unhelpfulCount": 81, "recommended": false, "verified": true, "purchasedDate": new Date("December 24, 2019"), "comments": [] },
    { "title": "ligula. Aenean euismod", "rating": 3, "user": "Ryan", "body": "ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet", "pics": [{ url: "https pic" }], "helpfulCount": 88, "unhelpfulCount": 98, "recommended": false, "verified": true, "purchasedDate": new Date("December 2, 2018"), "comments": [] },
    { "title": "mauris ut mi. Duis", "rating": 1, "user": "Elvis", "body": "enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at,", "pics": [{ url: "https pic" }], "helpfulCount": 11, "unhelpfulCount": 58, "recommended": false, "verified": true, "purchasedDate": new Date("September 10, 2019"), "comments": [] },
    {
        "title": "risus. Nunc ac sem ut", "rating": 1, "user": "Erica", "body": "et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi", "pics": [{ url: "https pic" }], "helpfulCount": 94, "unhelpfulCount": 20, "recommended": true, "verified": true, "purchasedDate": new Date("August 11, 2019"), "comments": []
    },
    { "title": "tincidunt, neque vitae semper egestas,", "rating": 3, "user": "Cynthia", "body": "Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh.", "pics": [{ url: "https pic" }], "helpfulCount": 99, "unhelpfulCount": 6, "recommended": false, "verified": true, "purchasedDate": new Date("February 25, 2019"), "comments": [] },
    { "title": "egestas lacinia. Sed congue, elit sed consequat", "rating": 5, "user": "Frances", "body": "lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci.", "pics": [{ url: "https pic" }], "helpfulCount": 75, "unhelpfulCount": 70, "recommended": false, "verified": false, "purchasedDate": new Date("November 19, 2019"), "comments": [] },
    { "title": "in sodales elit erat", "rating": 4, "user": "Drew", "body": "Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor", "pics": [{ url: "https pic" }], "helpfulCount": 75, "unhelpfulCount": 70, "recommended": false, "verified": true, "purchasedDate": new Date("April 19, 2019"), "comments": [] },
    { "title": "facilisi.", "rating": 1, "user": "Richard", "body": "sem magna nec quam. Curabitur vel", "pics": [{ url: "https pic" }], "helpfulCount": 20, "unhelpfulCount": 79, "recommended": true, "verified": true, "purchasedDate": new Date("June 1, 2018"), "comments": [] },
    { "title": "egestas. Fusce", "rating": 1, "user": "Philip", "body": "Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante", "pics": [{ url: "https pic" }], "helpfulCount": 81, "unhelpfulCount": 14, "recommended": false, "verified": true, "purchasedDate": new Date("April 11, 2019"), "comments": [] },
    { "title": "sapien, cursus", "rating": 5, "user": "Brandon", "body": "orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam", "pics": [{ url: "https pic" }], "helpfulCount": 39, "unhelpfulCount": 42, "recommended": true, "verified": false, "purchasedDate": new Date("March 13, 2019"), "comments": [] },
    { "title": "pellentesque. Sed", "rating": 5, "user": "Xena", "body": "amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", "pics": [{ url: "https pic" }], "helpfulCount": 83, "unhelpfulCount": 25, "recommended": true, "verified": true, "purchasedDate": new Date("November 11, 2019"), "comments": [] },
    { "title": "a, malesuada id, erat. Etiam vestibulum", "rating": 5, "user": "Ignatius", "body": "arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices", "pics": [{ url: "https pic" }], "helpfulCount": 68, "unhelpfulCount": 71, "recommended": true, "verified": true, "purchasedDate": new Date("October 16, 2019"), "comments": [] },
    { "title": "dignissim", "rating": 3, "user": "Hedy", "body": "adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam", "pics": [{ url: "https pic" }], "helpfulCount": 36, "unhelpfulCount": 20, "recommended": true, "verified": true, "purchasedDate": new Date("May 9, 2018"), "comments": [] },
    { "title": "gravida non, sollicitudin", "rating": 1, "user": "Jack", "body": "lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis", "pics": [{ url: "https pic" }], "helpfulCount": 2, "unhelpfulCount": 36, "recommended": false, "verified": true, "purchasedDate": new Date("March 5, 2020"), "comments": [] },
    { "title": "velit. Quisque varius. Nam porttitor", "rating": 1, "user": "Kelly", "body": "accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu,", "pics": [{ url: "https pic" }], "helpfulCount": 15, "unhelpfulCount": 80, "recommended": false, "verified": false, "purchasedDate": new Date("February 14, 2020"), "comments": [] },
    {
        "title": "condimentum.", "rating": 4, "user": "Melanie", "body": "cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices", "pics": [{ url: "https pic" }], "helpfulCount": 90, "unhelpfulCount": 88, "recommended": false, "verified": false, "purchasedDate": new Date("April 1, 2019"), "comments": [{ "user": "Rashad", "body": "sagittis augue, eu", "helpfulCount": 55, "unhelpfulCount": 73, "date": "June 13, 2018, " },
        { "user": "Cheyenne", "body": "rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id", "helpfulCount": 85, "unhelpfulCount": 60, "date": "July 19, 2018, " },
        { "user": "Uriel", "body": "eu erat semper rutrum. Fusce dolor quam,", "helpfulCount": 93, "unhelpfulCount": 85, "date": "May 5, 2019, " },
        { "user": "Bruce", "body": "facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non", "helpfulCount": 88, "unhelpfulCount": 95, "date": "June 14, 2019, " },
        { "user": "Shad", "body": "porttitor tellus non magna. Nam ligula", "helpfulCount": 16, "unhelpfulCount": 68, "date": "February 27, 2020, " },
        { "user": "Colt", "body": "ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat.", "helpfulCount": 51, "unhelpfulCount": 66, "date": "May 11, 2019, " },
        { "user": "Indigo", "body": "magna nec quam. Curabitur", "helpfulCount": 25, "unhelpfulCount": 38, "date": "October 1, 2018, " },
        { "user": "Gwendolyn", "body": "lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo.", "helpfulCount": 53, "unhelpfulCount": 82, "date": "January 13, 2020, " },
        { "user": "Whitney", "body": "sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel,", "helpfulCount": 81, "unhelpfulCount": 7, "date": "August 4, 2019, " },
        { "user": "Virginia", "body": "non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper", "helpfulCount": 27, "unhelpfulCount": 26, "date": "March 2, 2020, " },
        { "user": "Flynn", "body": "Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus", "helpfulCount": 49, "unhelpfulCount": 6, "date": "August 17, 2018, " },
        { "user": "Kenneth", "body": "non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate", "helpfulCount": 100, "unhelpfulCount": 82, "date": "October 17, 2019, " }]
    },
    { "title": "mauris, aliquam", "rating": 5, "user": "Rahim", "body": "gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit", "pics": [{ url: "https pic" }], "helpfulCount": 52, "unhelpfulCount": 14, "recommended": true, "verified": true, "purchasedDate": new Date("January 23, 2020"), "comments": [] },
    { "title": "Integer sem elit, pharetra", "rating": 1, "user": "Ferdinand", "body": "condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie", "pics": [{ url: "https pic" }], "helpfulCount": 36, "unhelpfulCount": 32, "recommended": true, "verified": true, "purchasedDate": new Date("May 15, 2018"), "comments": [] },
    { "title": "fringilla, porttitor vulputate, posuere vulputate, lacus.", "rating": 5, "user": "Brent", "body": "ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi,", "pics": [{ url: "https pic" }], "helpfulCount": 65, "unhelpfulCount": 7, "recommended": true, "verified": false, "purchasedDate": new Date("May 7, 2018"), "comments": [] },
    {
        "title": "dolor", "rating": 2, "user": "Risa", "body": "sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec", "pics": [{ url: "https pic" }], "helpfulCount": 16, "unhelpfulCount": 58, "recommended": false, "verified": true, "purchasedDate": new Date("March 15, 2020"), "comments": [{ "user": "Amanda", "body": "urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis", "helpfulCount": 90, "unhelpfulCount": 68, "date": "June 7, 2018, " },
        { "user": "Nissim", "body": "enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat.", "helpfulCount": 24, "unhelpfulCount": 29, "date": "May 2, 2018, " },
        { "user": "Talon", "body": "sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio.", "helpfulCount": 71, "unhelpfulCount": 58, "date": "November 13, 2019, " }]
    },
    {
        "title": "consectetuer adipiscing elit. Etiam", "rating": 5, "user": "Sage", "body": "mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus, at fringilla", "pics": [{ url: "https pic" }], "helpfulCount": 75, "unhelpfulCount": 87, "recommended": true, "verified": true, "purchasedDate": new Date("November 8, 2019"), "comments": []
    },
    { "title": "leo. Vivamus nibh dolor, nonummy", "rating": 1, "user": "Sydnee", "body": "egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu.", "pics": [{ url: "https pic" }], "helpfulCount": 98, "unhelpfulCount": 1, "recommended": true, "verified": true, "purchasedDate": new Date("March 17, 2020"), "comments": [] },
    { "title": "Nunc ac sem", "rating": 3, "user": "Jermaine", "body": "semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet,", "pics": [{ url: "https pic" }], "helpfulCount": 91, "unhelpfulCount": 60, "recommended": true, "verified": true, "purchasedDate": new Date("October 14, 2019"), "comments": [] },
    {
        "title": "lorem tristique", "rating": 3, "user": "Allen", "body": "Sed et libero. Proin mi. Aliquam gravida mauris ut", "pics": [{ url: "https pic" }], "helpfulCount": 68, "unhelpfulCount": 33, "recommended": true, "verified": false, "purchasedDate": new Date("October 1, 2018"), "comments": [{ "user": "Blaine", "body": "pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci,", "helpfulCount": 28, "unhelpfulCount": 42, "date": "September 16, 2019, " },
        { "user": "Brooke", "body": "neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi.", "helpfulCount": 87, "unhelpfulCount": 43, "date": "November 28, 2019, " }]
    },
    { "title": "Donec tempus, lorem fringilla ornare placerat, orci", "rating": 4, "user": "Isadora", "body": "odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat.", "pics": [{ url: "https pic" }], "helpfulCount": 88, "unhelpfulCount": 62, "recommended": false, "verified": true, "purchasedDate": new Date("March 26, 2019"), "comments": [] },
    { "title": "massa. Integer vitae nibh. Donec est mauris,", "rating": 2, "user": "Garrison", "body": "sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa.", "pics": [{ url: "https pic" }], "helpfulCount": 79, "unhelpfulCount": 1, "recommended": true, "verified": true, "purchasedDate": new Date("December 23, 2018"), "comments": [] },
    { "title": "Aliquam fringilla cursus purus. Nullam", "rating": 4, "user": "Victor", "body": "eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl.", "pics": [{ url: "https pic" }], "helpfulCount": 34, "unhelpfulCount": 39, "recommended": false, "verified": true, "purchasedDate": new Date("June 1, 2018"), "comments": [] },
    { "title": "sagittis lobortis mauris. Suspendisse aliquet molestie tellus.", "rating": 3, "user": "Maite", "body": "felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et", "pics": [{ url: "https pic" }], "helpfulCount": 4, "unhelpfulCount": 2, "recommended": true, "verified": true, "purchasedDate": new Date("December 9, 2019"), "comments": [] },
    { "title": "justo eu arcu. Morbi sit amet", "rating": 3, "user": "Zia", "body": "magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque", "pics": [{ url: "https pic" }], "helpfulCount": 45, "unhelpfulCount": 2, "recommended": false, "verified": true, "purchasedDate": new Date("January 10, 2020"), "comments": [] },
    { "title": "eu odio tristique pharetra.", "rating": 5, "user": "Kiona", "body": "vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit elit fermentum risus,", "pics": [{ url: "https pic" }], "helpfulCount": 12, "unhelpfulCount": 63, "recommended": true, "verified": false, "purchasedDate": new Date("May 24, 2018"), "comments": [] },
    { "title": "eu enim. Etiam imperdiet dictum", "rating": 3, "user": "Jesse", "body": "facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis", "pics": [{ url: "https pic" }], "helpfulCount": 47, "unhelpfulCount": 11, "recommended": false, "verified": true, "purchasedDate": new Date("September 17, 2019"), "comments": [] },
    {
        "title": "nibh", "rating": 3, "user": "Fredericka", "body": "urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id,", "pics": [{ url: "https pic" }], "helpfulCount": 95, "unhelpfulCount": 11, "recommended": true, "verified": false, "purchasedDate": new Date("August 26, 2019"), "comments": [{ "user": "Aquila", "body": "sem, vitae aliquam eros turpis non enim. Mauris quis", "helpfulCount": 15, "unhelpfulCount": 92, "date": "February 3, 2020, " },
        { "user": "Cleo", "body": "purus mauris a nunc. In at", "helpfulCount": 80, "unhelpfulCount": 82, "date": "March 26, 2019, " }]
    },
    { "title": "a, aliquet vel, vulputate eu,", "rating": 1, "user": "Zelenia", "body": "dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec", "pics": [{ url: "https pic" }], "helpfulCount": 26, "unhelpfulCount": 26, "recommended": false, "verified": false, "purchasedDate": new Date("December 12, 2019"), "comments": [] },
    { "title": "adipiscing lobortis risus. In mi pede,", "rating": 5, "user": "Dean", "body": "ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in", "pics": [{ url: "https pic" }], "helpfulCount": 27, "unhelpfulCount": 9, "recommended": false, "verified": true, "purchasedDate": new Date("April 28, 2018"), "comments": [] },
    {
        "title": "luctus lobortis. Class", "rating": 5, "user": "Violet", "body": "nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae,", "pics": [{ url: "https pic" }], "helpfulCount": 56, "unhelpfulCount": 7, "recommended": true, "verified": true, "purchasedDate": new Date("May 19, 2019"), "comments": []
    },
    { "title": "libero. Morbi accumsan", "rating": 4, "user": "Kim", "body": "risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada", "pics": [{ url: "https pic" }], "helpfulCount": 13, "unhelpfulCount": 42, "recommended": false, "verified": true, "purchasedDate": new Date("September 23, 2019"), "comments": [] },
    {
        "title": "orci sem eget massa. Suspendisse eleifend. Cras", "rating": 2, "user": "Karen", "body": "cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et", "pics": [{ url: "https pic" }], "helpfulCount": 13, "unhelpfulCount": 86, "recommended": false, "verified": false, "purchasedDate": new Date("August 13, 2018"), "comments": [{ "user": "Tasha", "body": "cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida", "helpfulCount": 96, "unhelpfulCount": 17, "date": "February 4, 2019, " },
        { "user": "George", "body": "tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum", "helpfulCount": 88, "unhelpfulCount": 31, "date": "November 13, 2018, " }]
    },
    { "title": "vulputate mauris sagittis", "rating": 4, "user": "Zenia", "body": "Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in", "pics": [{ url: "https pic" }], "helpfulCount": 17, "unhelpfulCount": 34, "recommended": true, "verified": true, "purchasedDate": new Date("February 19, 2020"), "comments": [] },
    { "title": "ut quam vel sapien", "rating": 1, "user": "Steven", "body": "quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus.", "pics": [{ url: "https pic" }], "helpfulCount": 48, "unhelpfulCount": 83, "recommended": true, "verified": true, "purchasedDate": new Date("April 4, 2019"), "comments": [] },
    { "title": "nunc sit amet metus.", "rating": 2, "user": "Jermaine", "body": "Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique", "pics": [{ url: "https pic" }], "helpfulCount": 71, "unhelpfulCount": 53, "recommended": false, "verified": true, "purchasedDate": new Date("January 5, 2020"), "comments": [] },
    { "title": "cursus et, eros. Proin ultrices. Duis", "rating": 3, "user": "Dale", "body": "dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et", "pics": [{ url: "https pic" }], "helpfulCount": 98, "unhelpfulCount": 81, "recommended": true, "verified": false, "purchasedDate": new Date("May 2, 2019"), "comments": [] },
    { "title": "Cum", "rating": 1, "user": "Dara", "body": "orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec", "pics": [{ url: "https pic" }], "helpfulCount": 10, "unhelpfulCount": 42, "recommended": false, "verified": false, "purchasedDate": new Date("May 12, 2019"), "comments": [{ "user": "Melissa", "body": "molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc", "helpfulCount": 43, "unhelpfulCount": 34, "date": "September 23, 2018, " }] },
    { "title": "eget, venenatis a,", "rating": 5, "user": "Gannon", "body": "ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit", "pics": [{ url: "https pic" }], "helpfulCount": 75, "unhelpfulCount": 59, "recommended": false, "verified": true, "purchasedDate": new Date("May 19, 2018"), "comments": [] },
    { "title": "ut nisi a", "rating": 5, "user": "Kuame", "body": "condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec", "pics": [{ url: "https pic" }], "helpfulCount": 3, "unhelpfulCount": 88, "recommended": false, "verified": true, "purchasedDate": new Date("February 25, 2019"), "comments": [] },
    { "title": "semper", "rating": 1, "user": "Vielka", "body": "Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam", "pics": [{ url: "https pic" }], "helpfulCount": 8, "unhelpfulCount": 56, "recommended": true, "verified": true, "purchasedDate": new Date("January 30, 2019"), "comments": [] },
    { "title": "ullamcorper, nisl arcu iaculis", "rating": 1, "user": "Eagan", "body": "Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas", "pics": [{ url: "https pic" }], "helpfulCount": 72, "unhelpfulCount": 92, "recommended": false, "verified": false, "purchasedDate": new Date("May 26, 2019"), "comments": [] },
    { "title": "nascetur ridiculus", "rating": 2, "user": "Gisela", "body": "sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie", "pics": [{ url: "https pic" }], "helpfulCount": 72, "unhelpfulCount": 49, "recommended": true, "verified": false, "purchasedDate": new Date("December 23, 2019"), "comments": [] },
    { "title": "semper et, lacinia vitae, sodales at,", "rating": 1, "user": "Ross", "body": "blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum", "pics": [{ url: "https pic" }], "helpfulCount": 39, "unhelpfulCount": 24, "recommended": false, "verified": false, "purchasedDate": new Date("August 6, 2018"), "comments": [] },
    { "title": "Aliquam nisl. Nulla eu", "rating": 1, "user": "Orson", "body": "eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in", "pics": [{ url: "https pic" }], "helpfulCount": 35, "unhelpfulCount": 100, "recommended": false, "verified": false, "purchasedDate": new Date("April 24, 2019"), "comments": [] },
    { "title": "gravida. Praesent", "rating": 2, "user": "Lev", "body": "et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique", "pics": [{ url: "https pic" }], "helpfulCount": 71, "unhelpfulCount": 3, "recommended": false, "verified": false, "purchasedDate": new Date("December 14, 2019"), "comments": [] },
    { "title": "nulla. In tincidunt congue turpis.", "rating": 4, "user": "Jelani", "body": "primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor", "pics": [{ url: "https pic" }], "helpfulCount": 10, "unhelpfulCount": 41, "recommended": false, "verified": true, "purchasedDate": new Date("November 30, 2018"), "comments": [] },
    { "title": "a, malesuada id, erat. Etiam vestibulum", "rating": 5, "user": "Tobias", "body": "nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur", "pics": [{ url: "https pic" }], "helpfulCount": 64, "unhelpfulCount": 51, "recommended": false, "verified": false, "purchasedDate": new Date("March 15, 2019"), "comments": [] },
    { "title": "molestie pharetra nibh. Aliquam", "rating": 1, "user": "Destiny", "body": "adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas", "pics": [{ url: "https pic" }], "helpfulCount": 58, "unhelpfulCount": 55, "recommended": true, "verified": true, "purchasedDate": new Date("February 4, 2020"), "comments": [] },
    { "title": "in molestie tortor nibh", "rating": 4, "user": "Abdul", "body": "sit amet, risus. Donec nibh enim, gravida sit amet,", "pics": [{ url: "https pic" }], "helpfulCount": 89, "unhelpfulCount": 21, "recommended": false, "verified": false, "purchasedDate": new Date("July 29, 2019"), "comments": [] },
    { "title": "ornare egestas ligula. Nullam", "rating": 3, "user": "Rhoda", "body": "Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem", "pics": [{ url: "https pic" }], "helpfulCount": 87, "unhelpfulCount": 83, "recommended": false, "verified": false, "purchasedDate": new Date("March 10, 2020"), "comments": [] },
    { "title": "lectus sit amet luctus vulputate, nisi sem", "rating": 4, "user": "Fletcher", "body": "habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat", "pics": [{ url: "https pic" }], "helpfulCount": 80, "unhelpfulCount": 71, "recommended": false, "verified": true, "purchasedDate": new Date("August 27, 2018"), "comments": [] },
    {
        "title": "et tristique pellentesque, tellus sem", "rating": 2, "user": "Maisie", "body": "justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna.", "pics": [{ url: "https pic" }], "helpfulCount": 50, "unhelpfulCount": 78, "recommended": false, "verified": true, "purchasedDate": new Date("September 13, 2018"), "comments": []
    },
    { "title": "vestibulum", "rating": 3, "user": "Calista", "body": "Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit", "pics": [{ url: "https pic" }], "helpfulCount": 85, "unhelpfulCount": 47, "recommended": true, "verified": false, "purchasedDate": new Date("January 18, 2020"), "comments": [] },
    {
        "title": "ac ipsum. Phasellus", "rating": 5, "user": "Wing", "body": "pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies", "pics": [{ url: "https pic" }], "helpfulCount": 90, "unhelpfulCount": 7, "recommended": true, "verified": false, "purchasedDate": new Date("January 25, 2020"), "comments": [{ "user": "Ginger", "body": "et, lacinia vitae, sodales", "helpfulCount": 21, "unhelpfulCount": 42, "date": "January 27, 2020, " },
        { "user": "Amber", "body": "parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl.", "helpfulCount": 9, "unhelpfulCount": 76, "date": "February 22, 2020, " },
        { "user": "Stacey", "body": "amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie", "helpfulCount": 14, "unhelpfulCount": 33, "date": "February 6, 2019, " },
        { "user": "Abraham", "body": "sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie", "helpfulCount": 23, "unhelpfulCount": 51, "date": "January 27, 2019, " },
        { "user": "Suki", "body": "nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper", "helpfulCount": 49, "unhelpfulCount": 78, "date": "June 4, 2019, " },
        { "user": "Reese", "body": "ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit,", "helpfulCount": 72, "unhelpfulCount": 45, "date": "May 25, 2018, " },
        { "user": "Anthony", "body": "semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices", "helpfulCount": 92, "unhelpfulCount": 3, "date": "October 16, 2018, " },
        { "user": "Demetria", "body": "auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In", "helpfulCount": 74, "unhelpfulCount": 20, "date": "June 26, 2018, " },
        { "user": "Andrew", "body": "egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac", "helpfulCount": 88, "unhelpfulCount": 14, "date": "January 5, 2019, " },
        { "user": "Whilemina", "body": "lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam", "helpfulCount": 70, "unhelpfulCount": 58, "date": "July 6, 2018, " },
        { "user": "Maryam", "body": "risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per", "helpfulCount": 9, "unhelpfulCount": 21, "date": "November 6, 2018, " },
        { "user": "Cassidy", "body": "interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In", "helpfulCount": 73, "unhelpfulCount": 96, "date": "May 11, 2019, " },
        { "user": "Hilary", "body": "aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam", "helpfulCount": 91, "unhelpfulCount": 68, "date": "December 25, 2019, " },
        { "user": "Graham", "body": "ipsum cursus", "helpfulCount": 43, "unhelpfulCount": 24, "date": "October 19, 2019, " },
        { "user": "Preston", "body": "mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi", "helpfulCount": 84, "unhelpfulCount": 73, "date": "June 7, 2018, " },
        { "user": "Geoffrey", "body": "convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum", "helpfulCount": 69, "unhelpfulCount": 43, "date": "August 11, 2018, " },
        { "user": "Buckminster", "body": "conubia nostra, per inceptos hymenaeos.", "helpfulCount": 95, "unhelpfulCount": 86, "date": "September 27, 2018, " },
        { "user": "Avye", "body": "tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum", "helpfulCount": 31, "unhelpfulCount": 39, "date": "June 4, 2019, " },
        { "user": "Amy", "body": "varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis,", "helpfulCount": 75, "unhelpfulCount": 83, "date": "June 23, 2018, " },
        { "user": "Xavier", "body": "et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet,", "helpfulCount": 35, "unhelpfulCount": 100, "date": "October 17, 2019, " },
        { "user": "Lunea", "body": "urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non,", "helpfulCount": 91, "unhelpfulCount": 86, "date": "July 21, 2019, " },
        { "user": "Anastasia", "body": "nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec", "helpfulCount": 4, "unhelpfulCount": 5, "date": "July 15, 2018, " },
        { "user": "Danielle", "body": "neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin", "helpfulCount": 58, "unhelpfulCount": 99, "date": "August 4, 2018, " },
        { "user": "Sybil", "body": "elit pede, malesuada vel, venenatis vel,", "helpfulCount": 98, "unhelpfulCount": 83, "date": "January 1, 2019, " },
        { "user": "Irene", "body": "ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas", "helpfulCount": 25, "unhelpfulCount": 55, "date": "June 9, 2019, " },
        { "user": "Malik", "body": "eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris", "helpfulCount": 83, "unhelpfulCount": 35, "date": "June 16, 2018, " }]
    },
    { "title": "purus. Maecenas libero est, congue a, aliquet", "rating": 2, "user": "Colorado", "body": "eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla", "pics": [{ url: "https pic" }], "helpfulCount": 3, "unhelpfulCount": 63, "recommended": true, "verified": true, "purchasedDate": new Date("December 23, 2019"), "comments": [] },
    { "title": "mi enim, condimentum eget, volutpat", "rating": 5, "user": "Veronica", "body": "tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat", "pics": [{ url: "https pic" }], "helpfulCount": 68, "unhelpfulCount": 78, "recommended": false, "verified": false, "purchasedDate": new Date("July 2, 2019"), "comments": [] },
    { "title": "Vivamus nisi. Mauris nulla. Integer urna. Vivamus", "rating": 2, "user": "Jayme", "body": "auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer", "pics": [{ url: "https pic" }], "helpfulCount": 35, "unhelpfulCount": 85, "recommended": false, "verified": false, "purchasedDate": new Date("July 18, 2019"), "comments": [] },
    { "title": "Aliquam", "rating": 2, "user": "Madaline", "body": "nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut", "pics": [{ url: "https pic" }], "helpfulCount": 46, "unhelpfulCount": 49, "recommended": true, "verified": false, "purchasedDate": new Date("May 11, 2018"), "comments": [] },
    { "title": "et, rutrum non, hendrerit id, ante. Nunc", "rating": 2, "user": "Leilani", "body": "quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula.", "pics": [{ url: "https pic" }], "helpfulCount": 47, "unhelpfulCount": 97, "recommended": true, "verified": false, "purchasedDate": new Date("February 25, 2019"), "comments": [] },
    { "title": "lectus", "rating": 1, "user": "Kirsten", "body": "vel quam dignissim pharetra. Nam ac nulla.", "pics": [{ url: "https pic" }], "helpfulCount": 60, "unhelpfulCount": 56, "recommended": false, "verified": false, "purchasedDate": new Date("February 21, 2020"), "comments": [] },
    { "title": "libero at auctor ullamcorper,", "rating": 2, "user": "Cedric", "body": "vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam", "pics": [{ url: "https pic" }], "helpfulCount": 38, "unhelpfulCount": 51, "recommended": true, "verified": false, "purchasedDate": new Date("March 11, 2020"), "comments": [] },
    { "title": "lectus sit amet", "rating": 2, "user": "Barrett", "body": "hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient", "pics": [{ url: "https pic" }], "helpfulCount": 86, "unhelpfulCount": 83, "recommended": true, "verified": false, "purchasedDate": new Date("May 19, 2019"), "comments": [] },
    { "title": "montes, nascetur ridiculus mus. Aenean eget", "rating": 3, "user": "Allegra", "body": "lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque.", "pics": [{ url: "https pic" }], "helpfulCount": 68, "unhelpfulCount": 21, "recommended": false, "verified": false, "purchasedDate": new Date("April 21, 2018"), "comments": [] },
    {
        "title": "pharetra,", "rating": 3, "user": "Nathan", "body": "in felis. Nulla tempor augue ac ipsum. Phasellus vitae", "pics": [{ url: "https pic" }], "helpfulCount": 74, "unhelpfulCount": 75, "recommended": true, "verified": true, "purchasedDate": new Date("August 3, 2018"), "comments": []
    },
    { "title": "Lorem ipsum dolor", "rating": 2, "user": "Aurora", "body": "tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc", "pics": [{ url: "https pic" }], "helpfulCount": 49, "unhelpfulCount": 98, "recommended": true, "verified": false, "purchasedDate": new Date("January 21, 2019"), "comments": [] },
    { "title": "vitae risus.", "rating": 4, "user": "Philip", "body": "ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce", "pics": [{ url: "https pic" }], "helpfulCount": 47, "unhelpfulCount": 100, "recommended": true, "verified": false, "purchasedDate": new Date("June 24, 2018"), "comments": [] },
    { "title": "condimentum. Donec at arcu. Vestibulum ante ipsum", "rating": 4, "user": "Denton", "body": "augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique", "pics": [{ url: "https pic" }], "helpfulCount": 54, "unhelpfulCount": 33, "recommended": false, "verified": true, "purchasedDate": new Date("July 24, 2019"), "comments": [] },
    { "title": "nibh. Donec", "rating": 5, "user": "Nita", "body": "magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer", "pics": [{ url: "https pic" }], "helpfulCount": 47, "unhelpfulCount": 65, "recommended": false, "verified": true, "purchasedDate": new Date("March 9, 2019"), "comments": [] },
    { "title": "neque vitae semper egestas, urna", "rating": 1, "user": "McKenzie", "body": "felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna,", "pics": [{ url: "https pic" }], "helpfulCount": 94, "unhelpfulCount": 67, "recommended": false, "verified": true, "purchasedDate": new Date("September 6, 2019"), "comments": [] },
    { "title": "Proin vel arcu eu odio tristique", "rating": 2, "user": "Xandra", "body": "iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque", "pics": [{ url: "https pic" }], "helpfulCount": 67, "unhelpfulCount": 34, "recommended": false, "verified": false, "purchasedDate": new Date("November 21, 2019"), "comments": [] },
    { "title": "Just a test", "rating": 4, "user": "Tatum", "body": "nibh. Aliquam ornare, libero at", "pics": [{ url: "https pic" }], "helpfulCount": 55, "unhelpfulCount": 28, "recommended": false, "verified": false, "purchasedDate": new Date("January 31, 2019"), "comments": [] }
]

const insertSamples = () => {
    Review.deleteMany({})
    .then(Review.create(samples))
    .then(() => console.log('ready to close mongo!'))
  }
  
  insertSamples();